name: Docker build and push

on:
  push:
    paths: freenom.sh
    branches: [master, main]
  pull_request:
  workflow_dispatch:

jobs:
  docker-images:
    name: Build Docker images and push to repositories
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        #with:
        #  token: ${{ secrets.TOKEN }}
      - name: Build images
        run: make docker
      #- name: Login to DockerHub
      #  uses: docker/login-action@v1
      #  with:
      #    username: ${{ secrets.DOCKERHUB_USERNAME }}
      #    password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}          
      - name: Push image
        run: |
          docker tag freenom-script:latest ghcr.io/mkorthof/freenom-script:latest
          docker tag freenom-script:alpine ghcr.io/mkorthof/freenom-script:alpine
          docker push ghcr.io/mkorthof/freenom-script:latest
          docker push ghcr.io/mkorthof/freenom-script:alpine
