name: Docker build and push

on:
  push:
    paths: freenom.sh
    branches: [master, main]
  pull_request:
  workflow_dispatch:

jobs:
  docker-images:
    name: Build Docker images and push to repositories
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        #with:
        #  token: ${{ secrets.TOKEN }}
      - name: Build Debian image
        run: |
          docker build -t freenom-script:latest -f- . <<EOF
          FROM debian:stable-slim
          ARG DEBIAN_FRONTEND=noninteractive
          ARG DEBCONF_NOWARNINGS="yes"
          COPY freenom.sh /usr/local/bin/
          COPY freenom.conf /usr/local/etc/
          RUN apt-get -yq update && apt-get -yq install --no-install-recommends curl ca-certificates bind9-dnsutils && rm -rf /var/lib/apt/lists/*
          USER nobody
          ENTRYPOINT [ "/usr/local/bin/freenom.sh" ]
          EOF
      - name: Build Alpine image
        run: |
          docker build -t freenom-script:alpine -f- . <<EOF
          FROM alpine:latest
          COPY freenom.sh /usr/local/bin/
          COPY freenom.conf /usr/local/etc/
          RUN apk update && apk add --no-cache curl ca-certificates bind-tools
          USER nobody
          ENTRYPOINT [ "/usr/local/bin/freenom.sh" ]
      #- name: Login to DockerHub
      #  uses: docker/login-action@v1
      #  with:
      #    username: ${{ secrets.DOCKERHUB_USERNAME }}
      #    password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}          
      - name: Push image
        run: |
          docker tag freenom-script:latest ghcr.io/mkorthof/freenom-script:latest
          docker tag freenom-script:alpine ghcr.io/mkorthof/freenom-script:alpine
          docker push ghcr.io/mkorthof/freenom-script:latest
          docker push ghcr.io/mkorthof/freenom-script:alpine
