name: Shellcheck

on: [push, pull_request, workflow_dispatch]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Set conf
              run: sed 's|/usr/local/etc/freenom.conf|freenom.sh|g' freenom.sh
            - name: Run shellcheck
              run: shellcheck -x freenom.sh
