name: Shellcheck

on: [push, pull_request, workflow_dispatch]
jobs:
    build:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v1
            - name: Run shellcheck
              run: shellcheck freenom.sh
