name: 'Freenom Renew'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 */9 * *'
 
jobs:
  Renew:
    runs-on: ubuntu-latest
    steps:
      - name: CheckOut
        uses: actions/checkout@v3
        
      - name: make
        run: sudo make install
      
      - name: Run script
        env: 
            freenom_email: ${{ secrets.EMAIL }}
            freenom_passwd: ${{ secrets.PASSWD }}
            APPRISE_SERVER_URLS: ${{ secrets.APPRISE }}
        run: sudo freenom.sh -r -a
