name: 'Freenom Renew'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 */9 * *'
 
jobs:
  Renew:
    runs-on: ubuntu-latest
    steps:
      - name: CheckOut
        uses: actions/checkout@v3
        
      - name: make
        env: 
            EMAIL: ${{ secrets.EMAIL }}
            PASSWD: ${{ secrets.PASSWD }}
            APPRISE_SERVER_URLS: ${{ secrets.APPRISE }}
        run: |
          sudo make install
          sudo sed -i "s/#freenom_email="you@example.com"/freenom_email="$EMAIL"/g" /usr/local/etc/freenom.conf
          sudo sed -i "s/#freenom_passwd="yourpassword"/freenom_passwd="$PASSWD"/g" /usr/local/etc/freenom.conf
          sudo cat /usr/local/etc/freenom.conf
      
      - name: Run script
        
        run: sudo freenom.sh -r -a
