name: Tests

on:
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Install freenom-script
        run: sudo make install
      - name: Install BATS
        run: git clone https://github.com/bats-core/bats-core.git && cd bats-core && sudo ./install.sh /usr/local
      - name: Run all BATS tests
        run: test/test.sh all
